apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-chart.fullname" . }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      {{- include "nginx-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-chart.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: init-copy-html
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - cp /src/index.html /usr/share/nginx/html/
          volumeMounts:
            - name: html-source
              mountPath: /src
            - name: nginx-storage
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: {{ .Values.nginx.containerPort }}
          volumeMounts:
            - name: nginx-storage
              mountPath: {{ .Values.nginx.mountPath }}
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc
        - name: html-source
          configMap:
            name: nginx-html
