apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-chart.fullname" . }}-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.annotations.scheme | quote }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingress.annotations.listenPorts | quote }}
    alb.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.annotations.sslRedirect | quote }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.annotations.targetType | quote }}
    {{- if .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nginx-chart.fullname" . }}-lb
                port:
                  number: {{ .Values.nginx.containerPort }}
