apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-chart.fullname" . }}-ingress
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nginx-chart.fullname" . }}-lb
                port:
                  number: {{ .Values.nginx.containerPort }}
