apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx-chart.fullname" . }}-pvc
spec:
  accessModes:
    - {{ .Values.storage.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
{{- if .Values.storage.storageClassName }}
{{- printf "storageClassName: %q" .Values.storage.storageClassName | nindent 2 }}
{{- end }}
