storage:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: gp2  # AWS EBS storage class
  persistentVolumeReclaimPolicy: Delete
  fsType: ext4
  

nginx:
  replicas: 1
  image: nginx:latest
  containerPort: 80
  mountPath: /usr/share/nginx/html

service:
  type: LoadBalancer  # Change to ClusterIP when needed
