storage:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: gp2  # AWS EBS storage class
  persistentVolumeReclaimPolicy: Delete
  fsType: ext4

app: nginx

nginx:
  replicas: 2
  image: nginx:latest
  containerPort: 80
  mountPath: /usr/share/nginx/html

service:
  type: LoadBalancer  # Change to ClusterIP when needed

ingress:
  enabled: true
  host: myapp.example.com
  certificateArn: arn:aws:acm:ap-southeast-2:123456789012:certificate/abcde1234-5678-90ab-cdef-cd34rf

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip



html:
  index: |
    <html>
      <head><title>{{ .Release.Name }} - Welcome</title></head>
      <body>
        <h1>Deployed by Helm!</h1>
      </body>
    </html>

controller:
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "${terraform.output.ebs_csi_driver_role_arn}"






