apiVersion: v2
name: nginx
description: A Helm chart for deploying NGINX with TLS
type: application
version: 1.0.0
appVersion: "1.25.3" # Latest stable NGINX
dependencies:
  - name: ingress-nginx
    version: "4.7.1"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress-nginx.enabled