name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install or Update AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Install Terraform
        run: |
            echo "Downloading Terraform..."
            curl -LO https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
            ls -lah terraform_1.5.0_linux_amd64.zip || echo "Terraform ZIP not found!"
        
            echo "Extracting Terraform..."
            unzip -f terraform_1.5.0_linux_amd64.zip
            ls -lah || echo "No Terraform binary found!"
            file terraform* || echo "Terraform binary missing!"
        
            echo "Checking extracted files..."
            if [ -f "terraform" ]; then
              echo "Terraform binary extracted successfully."
              sudo mv terraform /usr/local/bin/terraform
            elif [ -f "terraform/terraform" ]; then
              echo "Terraform binary found inside directory, moving..."
              sudo mv terraform/terraform /usr/local/bin/terraform
            else
              echo "Terraform binary is missing after extraction!"
              exit 1
            fi
        
            echo "Setting permissions..."
            sudo chmod +x /usr/local/bin/terraform
            ls -lah /usr/local/bin/terraform || echo "Terraform still missing after move!"
        
            echo "Adding Terraform to PATH..."
            echo "export PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV
            source $GITHUB_ENV
        
            echo "Verifying Terraform installation..."
            terraform version || echo "Terraform command not found!"
        
        
        
          
      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Apply Terraform
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Setup kubectl
        run: |
          aws eks update-kubeconfig --region ap-southeast-2 --name sammut-cluster
          kubectl get nodes

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy Nginx using Helm
        run: |
          helm upgrade --install nginx-release ./nginx-chart
