name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install or Update AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -LO https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
          
          # If terraform exists and is a directory, remove it
          if [ -d "/usr/local/bin/terraform" ]; then
            echo "Removing existing Terraform directory..."
            sudo rm -rf /usr/local/bin/terraform
          fi

          # If terraform exists as a file, remove it
          if [ -f "/usr/local/bin/terraform" ]; then
            echo "Removing existing Terraform binary..."
            sudo rm -f /usr/local/bin/terraform
          fi

          # Extract and install Terraform
          unzip -o terraform_1.5.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          ls -lah /usr/local/bin/terraform  # Verify installation
          terraform --version  # Verify installation


      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Apply Terraform
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Setup kubectl
        run: |
          aws eks update-kubeconfig --region ap-southeast-2 --name sammut-cluster
          kubectl get nodes

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy Nginx using Helm
        run: |
          helm upgrade --install nginx-release ./nginx-chart
