name: Deploy to AWS EKS #

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: ap-southeast-2
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~0.13.0

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        id: apply
        run: |
          cd terraform
          terraform apply -auto-approve
        continue-on-error: true



      - name: Save Terraform State
        run: |
          cd terraform
          tar -czf terraform-state.tar.gz terraform.tfstate
      - uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: terraform/terraform-state.tar.gz

      - name: Setup kubectl
        if: steps.apply.outcome == 'success'
        run: |
          aws eks update-kubeconfig --region ap-southeast-2 --name my-k8s-cluster
          kubectl get nodes

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-southeast-2 --name my-k8s-cluster

      - name: Install Helm
        if: steps.apply.outcome == 'success'
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy AWS EBS CSI Driver
        run: |
            helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
            helm repo update
            helm upgrade --install aws-ebs-csi-driver aws-ebs-csi-driver/aws-ebs-csi-driver \
              --namespace kube-system \
              --set controller.serviceAccount.create=true \
              --set controller.serviceAccount.name=ebs-csi-controller-sa \
              --set controller.serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=arn:aws:iam::843960079237:role/GHA-EBSCSIDRIVER
  
      - name: Verify Deployment
        run: |
            kubectl get pods -n kube-system
            kubectl get svc -n kube-system
