name: Update OIDC Trust Relationship

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3am UTC
  workflow_dispatch:

jobs:
  update-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2

      - name: Make script executable
        run: chmod +x scripts/update-oidc-trust.sh

      - name: Update OIDC trust relationship
        run: ./scripts/update-oidc-trust.sh
