name: packer
description: AMI build with Packer

inputs:
  working_dir:
    description: folder in the repo containing codebase
    default: packer
  is_dry_run:
    description: Dry-run only?
    default: true
  git_version:
    description: "Github repo version used to deploy infra. Ex: 2.0.0, 1.1.0, main"
    default: ${{ github.ref_name }}
  chg_number:
    description: CHG number
    default: N/A

runs:
  using: composite
  steps:
    - name: Check version
      run: packer version
      shell: bash
    - name: Init
      run: packer init .
      env:
        PKR_VAR_git_version: ${{ inputs.git_version }}
        PKR_VAR_chg_number: ${{ inputs.chg_number }}
      shell: bash
      working-directory: ${{ inputs.working_dir }}
    - name: Lint
      run: packer fmt -check .
      shell: bash
      working-directory: ${{ inputs.working_dir }}
    - name: Validate
      run: packer validate .
      env:
        PKR_VAR_git_version: ${{ inputs.git_version }}
        PKR_VAR_chg_number: ${{ inputs.chg_number }}
      shell: bash
      working-directory: ${{ inputs.working_dir }}
    - name: Build
      run: packer build .
      env:
        PKR_VAR_git_version: ${{ inputs.git_version }}
        PKR_VAR_chg_number: ${{ inputs.chg_number }}
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      if: inputs.is_dry_run == 'false'
